[package]
name = "jmex"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["small-buf"]

small-buf = []

[dependencies]
clap = "3.0.0-beta.2"
thiserror = "1"